version: '3.5'

networks:
  42intra:
    name: 42intra
    driver: bridge

services:
  mysql:
    image: mariadb
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    restart: always
    build: requirements/db/
    user: root
    networks:
      - 42intra
    container_name: mariadb
  nginx:
    image: nginx
    volumes:
      - wp:/var/www/html
    depends_on:
      - wp
    ports:
      - "443:443"
    env_file: .env
    restart: always
    build: requirements/nginx/
    user: root
    networks:
      - 42intra
    container_name: nginx
  wp:
    image: wordpress
    env_file: .env
    depends_on:
      - mysql
    volumes:
      - wp:/var/www/html
    restart: always
    build: requirements/wp/
    user: root
    networks:
      - 42intra
    container_name: wordpress

volumes:
  wp:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/gkelsie/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/gkelsie/data/mariadb
